# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6c0251cb55f2efe6bc024a4e8b187a543c75a4a5a2da914dd0f3950c957b638f1a2e77db60c8407c17b769e231f2bb23afec4ca9c37c56e24a48a3f6dd235359

test:
  secret_key_base: 163d1e7fbebca90e75e7a8825da9a82010ec37341a317b54a03b4404f9671dd4c1172d40d3f55c77df72f23d4a584c272522d3dbb1ab72579cfa6cb3fae9d65a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
